### ISSUE TITLE
如何处理Matterport3D数据

### ISSUE THREAD

**Issue by yehx1** [EnyaHermite/CircNet#1]
你好！非常感谢。我尝试使用Matterport3D数据，点云为bed1a77d92d64f5cbbaaae4feed64ec1.obj。直接使用的化内存占用比较大，降采样后模型出现较多孔洞。我想请问一下如何处理Matterport3D数据呢？

**Comment by EnyaHermite** [comment]
We uniformly sample 0.5Million points from the original mesh, but split them into several volume chunks such that the point cloud in one chunk can fit in the memory. Each chunk is processed individually using CircNet.

**Comment by yehx1** [comment]
Thanks a lot.
