### ISSUE TITLE
About ABC Dataset

### ISSUE THREAD

**Issue by shiyuze991202** [EnyaHermite/CircNet#2]
The link you provided for Download your voxelized [ABC](https://deep-geometry.github.io/abc-dataset/) subset has expired. Could you please provide it again?

**Comment by EnyaHermite** [comment]
seems to be issue related to the gdown version. You can try upgrade gdown with 'pip install --upgrade gdown', and run the download script again. 

If the above solution doesn't work, you can download the data manually from  'https://drive.google.com/uc?id=16LE2h4n-T1dEfZ2oN1SrOeq6w33FQW7k'.
